### ISSUE TITLE
RF Explorer 6G Combo PLUS Python library issue?

### ISSUE THREAD

**Issue by omardude** [RFExplorer/RFExplorer-for-Python#21]
Hi all, Recently purchased the RF Explorer 6G Combo PLUS and am having issues running the examples. The RFExplorer connects successfully and reads serial number but errors out at the following when running any of the examples. Is there any workaround?
Thanks!

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/xxxxxx/code/RFExplorer-for-Python/RFExplorer/ReceiveSerialThread.py", line 47, in run
    self.ReceiveThreadfunc()
  File "/Users/xxxxxx/code/RFExplorer-for-Python/RFExplorer/ReceiveSerialThread.py", line 117, in ReceiveThreadfunc
    nSize+=int(strReceived[3]) + 4
ValueError: invalid literal for int() with base 10: '\x03'
```

**Comment by omardude** [comment]
I believe the issue is related to the new configuration data format on the 6G Combo PLUS. Support mentioned fixing issue in the next couple weeks.

**Comment by winfield92** [comment]
Anyone aware of a resolution for this issue?

**Comment by omardude** [comment]
Any updates or insight on how the new configuration data is formatted? Thanks

**Comment by jcalderon09** [comment]
The new version of the RF Explorer libraries and examples for Python are already available for the new RF Explorer models. With this update you can already handle your 6G Combo PLUS.

**Comment by omardude** [comment]
Hello, I just tried the new updates on my 6G combo plus and am getting a similar error. I updated the firmware to the latest version as well: 3.29. I tried the three examples: RFE_Example_USB_1.py,  RFE_Example_USB_2.py, and RFE_Example_control.py. 

Any ideas? Thanks


Connected: /dev/cu.SLAB_USBtoUART, 500000 bauds
²º¯ª­°´«¬®´®¯´¬¬¬«©©«³¼¯°­­µ§±¬±©²´©««´¯¬°¬½¨´§¯¬«­®­²°«®­­°§«ª°¯±®²®°¯³
Device serial number: xxxxxxxx
#xxxxxxxx
Received RF Explorer device model info:#C2-M:010,014,03.29
ProcessReceivedString: 14 is not a valid eModel
#QA:0
New Freq range - buffer cleared.
#a0
Device serial number: xxxxxxxx
#xxxxxxxx
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/xxxxxxxx/code/xxxxxxxx/venv/lib/python3.8/site-packages/RFExplorer/ReceiveSerialThread.py", line 47, in run
    self.ReceiveThreadfunc()
  File "/Users/xxxxxxxx/code/xxxxxxxx/venv/lib/python3.8/site-packages/RFExplorer/ReceiveSerialThread.py", line 117, in ReceiveThreadfunc
    nSize+=int(strReceived[3]) + 4
ValueError: invalid literal for int() with base 10: '\x03'

**Comment by jcalderon09** [comment]
Hi Omar,

It seems you are not using the latest python library version. Please update to v1.33.2106.3​​ as described on [wiki](https://github.com/RFExplorer/RFExplorer-for-Python/wiki/Installing-RFExplorer-Python-library)

**Comment by jcalderon09** [comment]
We've updated the [release](https://github.com/RFExplorer/RFExplorer-for-Python/releases) to new v1.33.2106.3
